(function(){
'use strict';
const EXACT={
 hiyuki:{set:'소리 없이 내려앉은 기도의 눈 5세트',alt:'야밤의 서리 5세트',main:'글로모스',cost:'4-3-3-1-1',c4:'치명타 확률 / 치명타 피해',c3:'응결 피해 ×2',c1:'공격력% ×2',subs:['공명 효율 120%까지','치명타 확률','치명타 피해','공격력%','공명 해방 피해'],farm:'데이터뱅크 → 글로모스 → 탐지. 해당 잔향 무음 구역에서 파밍.',source:'Prydwen 기반 · 2026-07',mode:'개인 딜',reason:'조합과 무관하게 개인 딜 세팅 우선도가 높음'},
 lucilla:{set:'소리 없이 내려앉은 기도의 눈 5세트',alt:'떠오르는 구름 5세트',main:'글로모스',cost:'4-3-3-1-1',c4:'치명타 확률 / 치명타 피해',c3:'응결 피해 ×2',c1:'공격력% ×2',subs:['공명 효율 필요량까지','치명타 확률','치명타 피해','공격력%','일반 공격 피해'],farm:'데이터뱅크 → 글로모스 → 탐지. 해당 잔향 무음 구역에서 파밍.',source:'Prydwen 기반 · 2026-07',mode:'개인 딜',reason:'기본적으로 개인 피해 세팅이 안정적'},
 chisa:{set:'찬란한 광휘 5세트',alt:'개인 딜: 운명을 붕괴시키는 현 3세트 + 인멸 2세트',main:'돌아갈 곳이 없는 오류',altMain:'개인 딜 세팅: 전용 4코 에코',cost:'4-3-3-1-1',c4:'치명타 확률 / 치명타 피해',c3:'인멸 피해 ×2',c1:'공격력% ×2',subs:['공명 효율 125%까지','치명타 확률','치명타 피해','공격력%','공명 해방 피해'],farm:'데이터뱅크 → 돌아갈 곳이 없는 오류 → 탐지. 찬란한 광휘 무음 구역에서 파밍.',source:'Prydwen 기반 · 2026-07',mode:'팀 지원',reason:'지원 역할일 때 찬란한 광휘 효율이 안정적'}
};
const DMG={회절:'회절 피해',인멸:'인멸 피해',기류:'기류 피해',용융:'용융 피해',응결:'응결 피해',전도:'전도 피해'};
function team(ids){return ids.map(id=>window.state.chars.find(c=>c.id===id)).filter(Boolean)}
function build(c,ids){const mates=team(ids||[]),otherSup=mates.some(x=>x.id!==c.id&&x.role==='Support'),main=mates.some(x=>x.id!==c.id&&x.role==='Main DPS'),el=DMG[c.elem]||'속성 피해';if(c.role==='Support')return otherSup?{set:'떠오르는 구름 5세트',alt:'찬란한 광휘 5세트',main:'음험한 백로',cost:'4-3-3-1-1',c4:'치유 보너스 / 주 능력치%',c3:'공명 효율 ×2',c1:'주 능력치% ×2',subs:['공명 효율','주 능력치%','치명타','피해 보너스'],farm:'음험한 백로 탐지 + 떠오르는 구름 무음 구역',source:'조합 규칙 기반',mode:'버프 분담',reason:'다른 서포터가 있어 힐 세트 중복을 피함'}:{set:'찬란한 광휘 5세트',alt:'떠오르는 구름 5세트',main:'타종 거북이 / 돌아갈 곳이 없는 오류',cost:'4-3-3-1-1',c4:'치유 보너스 / 주 능력치%',c3:'공명 효율 ×2',c1:'주 능력치% ×2',subs:['공명 효율','주 능력치%','치명타','피해 보너스'],farm:'메인 에코 탐지 + 찬란한 광휘 무음 구역',source:'조합 규칙 기반',mode:'회복·지원',reason:'다른 서포터가 없어 회복과 팀 버프 우선'};if(c.role==='Sub DPS')return main?{set:'떠오르는 구름 5세트',alt:`${c.elem} 전용 딜 세트 5세트`,main:'음험한 백로 또는 전용 4코',cost:'4-3-3-1-1',c4:'치명타 확률 / 치명타 피해',c3:`${el} ×2`,c1:'공격력% ×2',subs:['공명 효율','치명타 확률','치명타 피해','공격력%'],farm:'메인 에코 탐지 + 떠오르는 구름 무음 구역',source:'조합 규칙 기반',mode:'메인 딜러 지원',reason:'메인 딜러가 있어 반주 버프 우선'}:{set:`${c.elem} 전용 딜 세트 5세트`,alt:'떠오르는 구름 5세트',main:'전용 4코 에코',cost:'4-3-3-1-1',c4:'치명타 확률 / 치명타 피해',c3:`${el} ×2`,c1:'공격력% ×2',subs:['치명타 확률','치명타 피해','공격력%','공명 효율'],farm:'전용 4코 탐지 + 해당 잔향 무음 구역',source:'조합 규칙 기반',mode:'서브 캐리',reason:'메인 딜러가 없어 개인 피해 우선'};return {set:`${c.elem} 전용 딜 세트 5세트`,alt:'끊임없는 잔향 2세트 혼합',main:'전용 4코 에코',cost:'4-3-3-1-1',c4:'치명타 확률 / 치명타 피해',c3:`${el} ×2`,c1:'공격력% ×2',subs:['치명타 확률','치명타 피해','공격력%','공명 효율'],farm:'전용 4코 탐지 + 해당 잔향 무음 구역',source:'조합 규칙 기반',mode:'메인 딜',reason:'메인 딜러는 개인 딜 세트 우선'};}
function exact(c,ids){const b=JSON.parse(JSON.stringify(EXACT[c.id]));if(c.id==='chisa'&&team(ids).some(x=>x.id!==c.id&&x.role==='Support')){b.set='떠오르는 구름 5세트';b.main='음험한 백로';b.mode='버프 분담';b.reason='다른 서포터가 찬란한 광휘를 맡아 치사는 반주 지원으로 전환'}return b}
window.WUWA_BUILD_DB={version:'5.0.0',getBuild(c,ids=[]){return EXACT[c.id]?exact(c,ids):build(c,ids)}};
})();