window.WUWA_DB_VERSION = '3.5-portrait-all-from-v3.4-2026-07-02';
window.WUWA_OPTIONS = {
  elements: ['전체','회절','인멸','기류','용융','응결','전도','미확정'],
  roles: ['전체','Main DPS','Sub DPS','Support','미확정'],
  weapons: ['직검','장검','권총','증폭기','권갑','미확정']
};
window.WUWA_CHARACTERS = [
  {
    "id": "sanhua",
    "kr": "산화",
    "en": "Sanhua",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_7.png"
  },
  {
    "id": "baizhi",
    "kr": "설지",
    "en": "Baizhi",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 2,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_6.png"
  },
  {
    "id": "lingyang",
    "kr": "능양",
    "en": "Lingyang",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_14.png"
  },
  {
    "id": "zhezhi",
    "kr": "절지",
    "en": "Zhezhi",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_27_UI.png"
  },
  {
    "id": "youhu",
    "kr": "유호",
    "en": "Youhu",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_31_UI.png"
  },
  {
    "id": "carlotta",
    "kr": "카를로타",
    "en": "Carlotta",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_32_UI.png"
  },
  {
    "id": "lucilla",
    "kr": "루실라",
    "en": "Lucilla",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_66_UI.png"
  },
  {
    "id": "hiyuki",
    "kr": "히유키",
    "en": "Hiyuki",
    "alias": [],
    "element": "응결",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_67_UI.png"
  },
  {
    "id": "chixia",
    "kr": "치샤",
    "en": "Chixia",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_2.png"
  },
  {
    "id": "encore",
    "kr": "앙코",
    "en": "Encore",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_8.png"
  },
  {
    "id": "mortefi",
    "kr": "모르테피",
    "en": "Mortefi",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_13.png"
  },
  {
    "id": "changli",
    "kr": "장리",
    "en": "Changli",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_26_UI.png"
  },
  {
    "id": "brant",
    "kr": "브렌트",
    "en": "Brant",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_44_UI.png"
  },
  {
    "id": "lupa",
    "kr": "루파",
    "en": "Lupa",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_46_UI.png"
  },
  {
    "id": "galbrena",
    "kr": "갈브레나",
    "en": "Galbrena",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_55_UI.png"
  },
  {
    "id": "mornye",
    "kr": "모니에",
    "en": "Mornye",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 2,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_61_UI.png"
  },
  {
    "id": "aemeath",
    "kr": "에이메스",
    "en": "Aemeath",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_53_UI.png"
  },
  {
    "id": "denia",
    "kr": "데니아",
    "en": "Denia",
    "alias": [],
    "element": "용융",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_64_UI.png"
  },
  {
    "id": "calcharo",
    "kr": "카카루",
    "en": "Calcharo",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_18.png"
  },
  {
    "id": "yinlin",
    "kr": "음림",
    "en": "Yinlin",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_17.png"
  },
  {
    "id": "yuanwu",
    "kr": "연무",
    "en": "Yuanwu",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_15.png"
  },
  {
    "id": "xiangliyao",
    "kr": "상리요",
    "en": "Xiangli Yao",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_25_UI.png"
  },
  {
    "id": "lumi",
    "kr": "루미",
    "en": "Lumi",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_30_UI.png"
  },
  {
    "id": "augusta",
    "kr": "아우구스타",
    "en": "Augusta",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_51_UI.png"
  },
  {
    "id": "buling",
    "kr": "복링",
    "en": "Buling",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 2,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_58_UI.png"
  },
  {
    "id": "rebecca",
    "kr": "레베카",
    "en": "Rebecca",
    "alias": [],
    "element": "전도",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_69_UI.png"
  },
  {
    "id": "yangyang",
    "kr": "양양",
    "en": "Yangyang",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_1.png"
  },
  {
    "id": "aalto",
    "kr": "알토",
    "en": "Aalto",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_12.png"
  },
  {
    "id": "jiyan",
    "kr": "기염",
    "en": "Jiyan",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_11.png"
  },
  {
    "id": "jianxin",
    "kr": "감심",
    "en": "Jianxin",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_23_UI.png"
  },
  {
    "id": "ciaccona",
    "kr": "샤콘",
    "en": "Ciaccona",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_37_UI.png"
  },
  {
    "id": "rover_aero",
    "kr": "방랑자 · 기류",
    "en": "Rover Aero",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_5.png"
  },
  {
    "id": "cartethyia",
    "kr": "카르티시아",
    "en": "Cartethyia",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_40_UI.png"
  },
  {
    "id": "iuno",
    "kr": "유노",
    "en": "Iuno",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_48_UI.png"
  },
  {
    "id": "qiuyuan",
    "kr": "구원",
    "en": "Qiuyuan",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_56_UI.png"
  },
  {
    "id": "sigrika",
    "kr": "시그리카",
    "en": "Sigrika",
    "alias": [],
    "element": "기류",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_65_UI.png"
  },
  {
    "id": "verina",
    "kr": "벨리나",
    "en": "Verina",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 2,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_3.png"
  },
  {
    "id": "rover_spectro",
    "kr": "방랑자 · 회절",
    "en": "Rover Spectro",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_5.png"
  },
  {
    "id": "jinhsi",
    "kr": "금희",
    "en": "Jinhsi",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_24_UI.png"
  },
  {
    "id": "shorekeeper",
    "kr": "파수인",
    "en": "The Shorekeeper",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 2,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_28_UI.png"
  },
  {
    "id": "phoebe",
    "kr": "페비",
    "en": "Phoebe",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_45_UI.png"
  },
  {
    "id": "zani",
    "kr": "젠니",
    "en": "Zani",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_38_UI.png"
  },
  {
    "id": "lynae",
    "kr": "린네",
    "en": "Lynae",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_60_UI.png"
  },
  {
    "id": "luuk",
    "kr": "루크 · 헤르센",
    "en": "Luuk Herssen",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_54_UI.png"
  },
  {
    "id": "lucy",
    "kr": "루시",
    "en": "Lucy",
    "alias": [],
    "element": "회절",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_68_UI.png"
  },
  {
    "id": "taoqi",
    "kr": "도기",
    "en": "Taoqi",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_9.png"
  },
  {
    "id": "danjin",
    "kr": "단근",
    "en": "Danjin",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_10.png"
  },
  {
    "id": "camellya",
    "kr": "카멜리아",
    "en": "Camellya",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_29_UI.png"
  },
  {
    "id": "rover_havoc",
    "kr": "방랑자 · 인멸",
    "en": "Rover Havoc",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_4.png"
  },
  {
    "id": "roccia",
    "kr": "로코코",
    "en": "Roccia",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_33_UI.png"
  },
  {
    "id": "cantarella",
    "kr": "칸타렐라",
    "en": "Cantarella",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_34_UI.png"
  },
  {
    "id": "phrolova",
    "kr": "플로로",
    "en": "Phrolova",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_41_UI.png"
  },
  {
    "id": "yangyang_xuanling",
    "kr": "양양·현령",
    "en": "Yangyang Xuanling",
    "alias": [
      "현령",
      "양양 현령",
      "SP양양",
      "양양SP"
    ],
    "element": "인멸",
    "weapon": "직검",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.5",
    "portrait": "https://lootbarcreator.fp.guinfra.com/file/6a3e7fb2240de358d7fce204hjuVDeTB03"
  },
  {
    "id": "chisa",
    "kr": "치사",
    "en": "Chisa",
    "alias": [],
    "element": "인멸",
    "weapon": "미확정",
    "role": "Support",
    "vigor": 2,
    "version": "~3.5",
    "portrait": "https://wuthering.gg/_ipx/q_70%26s_100x100/images/iconrolehead150/T_IconRoleHead150_57_UI.png"
  },
  {
    "id": "suisui",
    "kr": "수수",
    "en": "Suisui",
    "alias": [
      "Suisui"
    ],
    "element": "응결",
    "weapon": "증폭기",
    "role": "Support",
    "vigor": 2,
    "version": "~3.5",
    "portrait": "https://lootbarcreator.fp.guinfra.com/file/6a3e82dbfffd906d7a1b3d72R5dC0RAa03"
  },
  {
    "id": "qingxiao",
    "kr": "청초",
    "en": "Qingxiao",
    "alias": [
      "청소",
      "Qingxiao",
      "청샤오"
    ],
    "element": "기류",
    "weapon": "직검",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.6",
    "portrait": ""
  },
  {
    "id": "jingran",
    "kr": "경연",
    "en": "Jingran",
    "alias": [
      "Jingran",
      "징란"
    ],
    "element": "회절",
    "weapon": "권갑",
    "role": "Sub DPS",
    "vigor": 1,
    "version": "~3.6",
    "portrait": ""
  },
  {
    "id": "hsin",
    "kr": "여우의 별자리",
    "en": "Hsin",
    "alias": [
      "여우별",
      "심월호",
      "신",
      "Hsin",
      "Fox Constellation"
    ],
    "element": "전도",
    "weapon": "증폭기",
    "role": "Main DPS",
    "vigor": 1,
    "version": "~3.7",
    "portrait": ""
  },
  {
    "id": "suoming",
    "kr": "쇄명",
    "en": "Suoming",
    "alias": [
      "수밍",
      "Suoming"
    ],
    "element": "용융",
    "weapon": "권총",
    "role": "Support",
    "vigor": 2,
    "version": "~3.7",
    "portrait": ""
  }
];
