window.WUWA_DB_VERSION = '3.7-kor-db-2026-07-02';
window.WUWA_OPTIONS = {
  elements: ['전체','회절','인멸','기류','용융','응결','전도','미확정'],
  roles: ['전체','Main DPS','Sub DPS','Support','미확정'],
  weapons: ['직검','장검','권총','증폭기','권갑','미확정']
};
window.WUWA_CHARACTERS = [
  {id:'jinhsi', kr:'금희', en:'Jinhsi', alias:['금주령윤'], element:'회절', weapon:'장검', role:'Main DPS', vigor:1, version:'1.1'},
  {id:'changli', kr:'장리', en:'Changli', alias:[], element:'용융', weapon:'직검', role:'Main DPS', vigor:1, version:'1.1'},
  {id:'jiyan', kr:'기염', en:'Jiyan', alias:[], element:'기류', weapon:'장검', role:'Main DPS', vigor:1, version:'1.0'},
  {id:'yinlin', kr:'음림', en:'Yinlin', alias:[], element:'전도', weapon:'증폭기', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'verina', kr:'벨리나', en:'Verina', alias:[], element:'회절', weapon:'증폭기', role:'Support', vigor:2, version:'1.0'},
  {id:'zhezhi', kr:'절지', en:'Zhezhi', alias:[], element:'응결', weapon:'증폭기', role:'Sub DPS', vigor:1, version:'1.2'},
  {id:'xiangliyao', kr:'상리요', en:'Xiangli Yao', alias:['상리'], element:'전도', weapon:'권갑', role:'Main DPS', vigor:1, version:'1.2'},
  {id:'shorekeeper', kr:'파수인', en:'The Shorekeeper', alias:['쇼어키퍼'], element:'회절', weapon:'증폭기', role:'Support', vigor:2, version:'1.3'},
  {id:'camellya', kr:'카멜리아', en:'Camellya', alias:[], element:'인멸', weapon:'직검', role:'Main DPS', vigor:1, version:'1.4'},
  {id:'carlotta', kr:'카를로타', en:'Carlotta', alias:['카르로타'], element:'응결', weapon:'권총', role:'Main DPS', vigor:1, version:'2.0'},
  {id:'roccia', kr:'로코코', en:'Roccia', alias:[], element:'인멸', weapon:'권갑', role:'Sub DPS', vigor:1, version:'2.0'},
  {id:'phoebe', kr:'페비', en:'Phoebe', alias:[], element:'회절', weapon:'증폭기', role:'Main DPS', vigor:1, version:'2.1'},
  {id:'brant', kr:'브랜트', en:'Brant', alias:['브렌트'], element:'용융', weapon:'직검', role:'Support', vigor:1, version:'2.1'},
  {id:'cantarella', kr:'칸타렐라', en:'Cantarella', alias:[], element:'인멸', weapon:'증폭기', role:'Sub DPS', vigor:1, version:'2.2'},
  {id:'ciaccona', kr:'샤콘', en:'Ciaccona', alias:['시아코나'], element:'기류', weapon:'권총', role:'Sub DPS', vigor:1, version:'2.3'},
  {id:'zani', kr:'젠니', en:'Zani', alias:['자니'], element:'회절', weapon:'권갑', role:'Main DPS', vigor:1, version:'2.3'},
  {id:'cartethyia', kr:'카르티시아', en:'Cartethyia', alias:['카르테시아'], element:'기류', weapon:'직검', role:'Main DPS', vigor:1, version:'2.4'},
  {id:'lupa', kr:'루파', en:'Lupa', alias:['구원'], element:'용융', weapon:'장검', role:'Sub DPS', vigor:1, version:'2.4'},
  {id:'phrolova', kr:'플로로', en:'Phrolova', alias:[], element:'인멸', weapon:'증폭기', role:'Main DPS', vigor:1, version:'2.5'},
  {id:'augusta', kr:'아우구스타', en:'Augusta', alias:[], element:'전도', weapon:'장검', role:'Main DPS', vigor:1, version:'2.6'},
  {id:'iuno', kr:'유노', en:'Iuno', alias:['이우노'], element:'기류', weapon:'권갑', role:'Support', vigor:1, version:'2.6'},
  {id:'galbrena', kr:'갈브레나', en:'Galbrena', alias:[], element:'용융', weapon:'권총', role:'Main DPS', vigor:1, version:'2.7'},
  {id:'qiuyuan', kr:'구원', en:'Qiuyuan', alias:['루파'], element:'기류', weapon:'직검', role:'Sub DPS', vigor:1, version:'2.7'},
  {id:'chisa', kr:'치사', en:'Chisa', alias:[], element:'인멸', weapon:'권총', role:'Support', vigor:2, version:'2.8'},
  {id:'monie', kr:'모니에', en:'Monie', alias:[], element:'회절', weapon:'증폭기', role:'Support', vigor:2, version:'2.8'},
  {id:'hiyuki', kr:'히유키', en:'Hiyuki', alias:[], element:'응결', weapon:'권총', role:'Main DPS', vigor:1, version:'3.0'},
  {id:'lucilla', kr:'루실라', en:'Lucilla', alias:[], element:'인멸', weapon:'권총', role:'Sub DPS', vigor:1, version:'3.1'},
  {id:'rinne', kr:'린네', en:'Rinne', alias:[], element:'전도', weapon:'직검', role:'Sub DPS', vigor:1, version:'3.2'},
  {id:'aemes', kr:'에이메스', en:'Aemes', alias:[], element:'전도', weapon:'증폭기', role:'Main DPS', vigor:1, version:'3.3'},
  {id:'furling', kr:'복링', en:'Furling', alias:[], element:'회절', weapon:'증폭기', role:'Support', vigor:2, version:'3.3'},
  {id:'lucy', kr:'루시', en:'Lucy', alias:[], element:'용융', weapon:'권총', role:'Main DPS', vigor:1, version:'3.4'},
  {id:'rebecca', kr:'레베카', en:'Rebecca', alias:[], element:'전도', weapon:'권총', role:'Sub DPS', vigor:1, version:'3.4'},
  {id:'xuanling', kr:'양양·현령', en:'Xuanling', alias:['현령','양양SP','양양 현령'], element:'인멸', weapon:'직검', role:'Main DPS', vigor:1, version:'3.5'},
  {id:'suisui', kr:'수수', en:'Suisui', alias:[], element:'응결', weapon:'증폭기', role:'Support', vigor:2, version:'3.5'},
  {id:'qingchu', kr:'청초', en:'Qingxiao', alias:['청샤오','청소'], element:'기류', weapon:'직검', role:'Main DPS', vigor:1, version:'3.6'},
  {id:'jingyan', kr:'경연', en:'Jingran', alias:['징란'], element:'용융', weapon:'장검', role:'Sub DPS', vigor:1, version:'3.6'},
  {id:'foxfate', kr:'여우의 별자리', en:'Hsin', alias:['여우별','심월호','신'], element:'미확정', weapon:'미확정', role:'미확정', vigor:1, version:'3.7'},
  {id:'suoming', kr:'쇄명', en:'Suoming', alias:['수밍'], element:'미확정', weapon:'미확정', role:'Support', vigor:1, version:'3.7'},
  {id:'encore', kr:'앙코', en:'Encore', alias:[], element:'용융', weapon:'증폭기', role:'Main DPS', vigor:1, version:'1.0'},
  {id:'calcharo', kr:'카카루', en:'Calcharo', alias:[], element:'전도', weapon:'장검', role:'Main DPS', vigor:1, version:'1.0'},
  {id:'jianxin', kr:'감심', en:'Jianxin', alias:[], element:'기류', weapon:'권갑', role:'Support', vigor:1, version:'1.0'},
  {id:'baizhi', kr:'설지', en:'Baizhi', alias:[], element:'응결', weapon:'증폭기', role:'Support', vigor:2, version:'1.0'},
  {id:'rover_havoc', kr:'방랑자·인멸', en:'Rover Havoc', alias:['인멸랑자'], element:'인멸', weapon:'직검', role:'Main DPS', vigor:1, version:'1.0'},
  {id:'rover_spectro', kr:'방랑자·회절', en:'Rover Spectro', alias:['회절랑자'], element:'회절', weapon:'직검', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'rover_aero', kr:'방랑자·기류', en:'Rover Aero', alias:['기류랑자'], element:'기류', weapon:'직검', role:'Sub DPS', vigor:1, version:'2.x'},
  {id:'mortefi', kr:'모르테피', en:'Mortefi', alias:[], element:'용융', weapon:'권총', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'sanhua', kr:'산화', en:'Sanhua', alias:[], element:'응결', weapon:'직검', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'danjin', kr:'단근', en:'Danjin', alias:[], element:'인멸', weapon:'직검', role:'Main DPS', vigor:1, version:'1.0'},
  {id:'chixia', kr:'치샤', en:'Chixia', alias:[], element:'용융', weapon:'권총', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'yangyang', kr:'양양', en:'Yangyang', alias:[], element:'기류', weapon:'직검', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'yuanwu', kr:'연무', en:'Yuanwu', alias:[], element:'전도', weapon:'권갑', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'taoqi', kr:'도기', en:'Taoqi', alias:[], element:'인멸', weapon:'장검', role:'Support', vigor:1, version:'1.0'},
  {id:'aalto', kr:'알토', en:'Aalto', alias:[], element:'기류', weapon:'권총', role:'Sub DPS', vigor:1, version:'1.0'},
  {id:'lingyang', kr:'능양', en:'Lingyang', alias:[], element:'응결', weapon:'권갑', role:'Main DPS', vigor:1, version:'1.0'},
  {id:'youhu', kr:'유호', en:'Youhu', alias:[], element:'응결', weapon:'권갑', role:'Support', vigor:1, version:'1.3'},
  {id:'lumi', kr:'루미', en:'Lumi', alias:[], element:'전도', weapon:'장검', role:'Sub DPS', vigor:1, version:'1.4'}
];
